### ISSUE TITLE
copy support

### ISSUE THREAD

**Issue by nqyijian** [Developer-Mike/obsidian-docxer#11]

**Comment by nqyijian** [comment]
Thank you for your excellent plugin, it really helped me a lot.

**Comment by Developer-Mike** [comment]
Thank you for your suggestion. What do you mean by "copy support"? Do you mean the ability to select and copy text directly from the docx file without converting it first?

**Comment by nqyijian** [comment]
yes, i can copy to my another note.

**Comment by Developer-Mike** [comment]
Added in version `2.1.1`
