### ISSUE TITLE
What engine do it use?

### ISSUE THREAD

**Issue by pro-arch-user** [Developer-Mike/obsidian-docxer#13]
Hi. At first I thought that this is just a pandoc frontend, but I looked at the code and it doesn't look like it. Is it your own custom engine? It work amazing. Please clarify that in the plugin description. Also, any chance to get a command line version on this?

**Comment by Developer-Mike** [comment]
Hey 👋🏻. The plugin uses [this](https://www.npmjs.com/package/docx-preview) npm package to show the preview of the docx file and [mammoth](https://www.npmjs.com/package/mammoth) to convert the docx content to HTML. This HTML gets converted to markdown using the turndown service that Obsidian also uses internally for their inbuilt HTML to markdown conversion. [Here](https://github.com/Developer-Mike/obsidian-docxer/blob/6483ea72ddd645c629eeb6baa5a81a25e9c1cc12/src/convertable-file-views/docx.ts#L48-L124) is the relevant code. There are no plans to provide a command line tool for docxer (I have other stuff to do 🙄).

**Comment by pro-arch-user** [comment]
Nice! It would be cool if you could add this information to readme.md. Perhaps it would be useful to someone, like if they wanna create a command-line version of it.
