### ISSUE TITLE
On canvas view

### ISSUE THREAD

**Issue by AlexJankowski** [Developer-Mike/obsidian-docxer#14]
Many thanks for this wonderful plugin I am using it a lot.
One feature however that is missing and would be nice to have is on canvas view. 
For now when I try to place DOCX file on canvas it appears just as it would be an attached file.
Is it possible to add a preview feature on canvas similarly as it works natively with PDF files?

**Comment by Developer-Mike** [comment]
Version `2.1.0` adds support for embeds which also applies for the canvas.
