### ISSUE TITLE
have problem when change tables which have combined cells

### ISSUE THREAD

**Issue by Juan-hwt** [Developer-Mike/obsidian-docxer#15]
the combined cells will drift to the first cell (the combined one)

**Comment by Developer-Mike** [comment]
Docxer uses the npm plugin "docx-preview" for the word preview. Consider creating an issue there.

**Comment by Juan-hwt** [comment]
https://[volodymyrbaydalka.github.io/docxjs/](https://volodymyrbaydalka.github.io/docxjs/) 
this website works ok when docs have combined cells
you can try
