### ISSUE TITLE
[Feature Request] Add support to .doc files

### ISSUE THREAD

**Issue by Jiang10086** [Developer-Mike/obsidian-docxer#2]
I occasionally receive .doc files from others, it will a great help if .doc files is support by this plugin, so I can read .doc directly in Obsidian.
I have heard that even .doc and .docx looks similar, but are totally different, it may need great effort to achieve this.

**Comment by Developer-Mike** [comment]
Sorry for not replying. As you said, this feature would take a long time to implement. Especially because there is no library that supports .doc file parsing. So this feature is not planned.
