### ISSUE TITLE
[Feature Request] Importing Comments

### ISSUE THREAD

**Issue by Narifia** [Developer-Mike/obsidian-docxer#4]
First of all, *THANK YOU SO MUCH* for your amazing plugin! You have no idea how long I've searched for a plugin or solution to import my docx files without a ton of different external conversion tools (or Pandoc, which I can't get to work on mobile no matter what I do). I installed your plugin, popped a docx into my vault, and *instant success*, it was like magic 💖🥹

Now on to the feature request: Would it be possible to import comments in docx files, perhaps as footnotes or otherwise added on at the end? I realize importing them as straight-up comments would require coding in an entirely new functionality, so I thought this might be a simpler workaround. No idea how feasible it is, but I thought I'd toss the idea out there.

**Comment by Developer-Mike** [comment]
Thank you for your motivating words 😊.
I'll take a look at it. But it's very likely that support for comments will get added.

**Comment by Developer-Mike** [comment]
Added in version `2.0.0`
