### ISSUE TITLE
Can't get 1.0.2 -> 2.0 - install failed

### ISSUE THREAD

**Issue by merlinuwe** [Developer-Mike/obsidian-docxer#5]
When I update the plugins, I see this

![image](https://github.com/Developer-Mike/obsidian-docxer/assets/4138869/ecdab6fe-3ec5-409c-a94a-441290abd69d)

![image](https://github.com/Developer-Mike/obsidian-docxer/assets/4138869/a6e5db77-a4c4-4926-ba3c-2cc1882baeaa)

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.6.5
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.6.0
	Snippets enabled: 36
	Restricted mode: off
	Plugins installed: 149
	Plugins enabled: 58
		1: Set View Mode per Note v1.0.3
		2: Admonition v10.3.2
		3: Advanced Tables v0.21.0
		4: Advanced URI v1.40.1
		5: Android nomedia v0.1.0
		6: Auto Link Title v1.5.4
		7: Beautitab v1.6.1
		8: Better Export PDF v1.8.1
		9: Commander v0.5.1
		10: Colored Tags Wrangler v0.19.3
		11: Copy document as HTML v0.7.0
		12: Creases v0.7.0
		13: Custom Classes v2.6.1
		14: Dictionary v2.22.0
		15: Editing Toolbar v2.4.16
		16: Editor Commands Remap v1.0.2
		17: Editor Syntax Highlight v0.1.3
		18: Enhancing Export v1.10.6
		19: Excel to Markdown Table v0.4.0
		20: Export Image plugin v2.3.10
		21: File Explorer Note Count v1.2.2
		22: Google Calendar v1.10.14
		23: Linter v1.24.0
		24: Local Backup v0.1.7
		25: markdown export v1.0.21
		26: Natural Language Dates v0.6.2
		27: Navigate Cursor History v1.1.0
		28: Note Toolbar v1.7.28
		29: Number Headings v1.16.0
		30: Omnisearch v1.23.1
		31: Paste image rename v1.6.1
		32: Quick Explorer v0.2.8
		33: Quiet Outline v0.3.35
		34: Recent Files v1.4.1
		35: Scroll to Top v2.1.4
		36: Settings Management v1.0.5
		37: Sheet Plus v1.2.0
		38: Show Current File Path v0.5.2
		39: Sortable v0.3.1
		40: Status Bar Organizer v2.0.2
		41: Style Settings v1.0.8
		42: Supercharged Links v0.12.1
		43: Symbols Prettifier v1.1.4
		44: Tag Wrangler v0.6.1
		45: Tasks v7.5.0
		46: Templater v2.3.3
		47: Text Extractor v0.5.2
		48: Todo sort v1.0.0
		49: Translate v1.4.8
		50: Typing Transformer v0.4.0
		51: Vault Changelog v0.1.0
		52: Vault Statistics v0.1.3
		53: Webpage HTML Export v1.8.01
		54: Link Converter v0.1.6
		55: Date Inserter v0.3.3
		56: Dataview v0.5.67
		57: Desmos v0.6.8
		58: Docxer v1.0.2

What can I do to get the update?

**Comment by Developer-Mike** [comment]
There is no release 2.0.0 yet. It's a "bug" of Obsidian. Obsidian thinks there should be a more recent version but in reality there isn't one.

**Comment by merlinuwe** [comment]
I deinstalled it and cannot install anymore, even not the 1.0.2.

**Comment by Developer-Mike** [comment]
Oh... Didn't know that. But I probably will release the new version today.

**Comment by merlinuwe** [comment]
Thank you very much.
