### ISSUE TITLE
Failed to load plugin 

### ISSUE THREAD

**Issue by laArete** [Developer-Mike/obsidian-docxer#7]
After successfully installing the plugin on my IPhone, I am unable to load it. I am attempting to install version 2.0 directly from Obsidian.

**Comment by Developer-Mike** [comment]
Can you try it with version 1.0.2 and report if this version is working?

**Comment by laArete** [comment]
How do I do that on mobile?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by laArete** [comment]
I'm on iOS and cannot access hidden folders.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Developer-Mike** [comment]
I found the issue and resolved it in version `2.0.1`
