### ISSUE TITLE
Plugin update 2.0 -> 2.0 

### ISSUE THREAD

**Issue by merlinuwe** [Developer-Mike/obsidian-docxer#8]
Me again. ;-)

![image](https://github.com/Developer-Mike/obsidian-docxer/assets/4138869/c44e206e-51d9-4093-a7db-2506f7459a3c)

Every time I restart Obsidian and update the plugins, docxer thinks it has to update itself. But is is already on 2.0.

**Comment by Developer-Mike** [comment]
Have you tried reinstalling the plugin through the community plugins list?

**Comment by merlinuwe** [comment]
Yes, reinstalling solves the problem for now. After a restart of Obsidian there is no update available. But I worry, that the issue will come back after the next update of your plugin.

**Comment by Developer-Mike** [comment]
In the other issue you mentioned that you installed version 2.0.0 manually. This was before the official release, thus e.g. the main.js files didn't match. This, or improper manual updating, very likely caused the issue.

**Comment by Developer-Mike** [comment]
If this issue comes up again, feel free to reopen the issue 👍🏻
