### ISSUE TITLE
Embed preview support

### ISSUE THREAD

**Issue by calmwaves111** [Developer-Mike/obsidian-docxer#9]
Thank you for your excellent plugin, it really helped me a lot
I now have a request, can it support embedded preview like pdf?
Such as `![[test.docx]] ` or `![test] (test.docx)`

**Comment by Developer-Mike** [comment]
I apologize for the delay in my reply. This would certainly be a useful feature. Unfortunately, I don't think there is an official way to provide embeds for custom file types. But I'll take a look if that's possible.

**Comment by Developer-Mike** [comment]
Version `2.1.0` adds support for embeds 👍🏻. Thank you for the suggestion.
